### example测试
GET http://localhost:8080/api
Content-Type: application/json

###
POST http://localhost:8080/v1/version
Content-Type: application/json

{
  "input":"hello"
}

###
GET http://localhost:8080/v1/version?input=hello1