### example测试
GET http://localhost:8080/v1/version
Content-Type: application/json

###
GET http://localhost:8080/v1/version
Content-Type: application/json

{
  "input":"hello"
}

###
GET http://localhost:8080/v1/version?input=hello1
Content-Type: application/grpc+uri