version: "2"
issues:
  fix: true
linters:
  default: none
  enable:
    - govet
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/example
      - cmds
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
    - gofmt
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      # A list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      # Default: []
      local-prefixes:
        - github.com/pubgo/lava/v2
    gofmt:
      # Simplify code: gofmt with `-s` option.
      # Default: true
      simplify: false
      # Apply the rewrite rules to the source before reformatting.
      # https://pkg.go.dev/cmd/gofmt
      # Default: []
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'

  exclusions:
    paths:
      - internal/example
      - vendor
      - examples$
      - proto
