linters:
  fast: true
  disable-all: true
  enable:
    #    - bodyclose     # checks whether HTTP response body is closed successfully
    #    - errcheck      # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
    #    - gosimple      # Linter for Go source code that specializes in simplifying a code
    - govet         # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    #    - ineffassign   # Detects when assignments to existing variables are not used
    #    - dogsled       # Checks assignments with too many blank identifiers (e.g. x, , , _, := f())
    #    - goconst       # Finds repeated strings that could be replaced by a constant
    - goimports     # Goimports does everything that gofmt does. Additionally it checks unused imports
#    - goprintffuncname # Checks that printf-like functions are named with f at the end
#    - nolintlint     # Reports ill-formed or insufficient nolint directives
#    - rowserrcheck   # checks whether Err of rows is checked successfully
#    - staticcheck    # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
#    - unconvert      # Remove unnecessary type conversions
#    - unparam        # Reports unused function parameters
#    - unused         # Checks Go code for unused constants, variables, functions and types

issues:
  exclude-dirs:
    - vendor
  exclude-generated: strict
  exclude-dirs-use-default: true
  exclude-case-sensitive: false
  exclude-use-default: true
