[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""
body = """
{%- for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{%- for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}\
  {%- if commit.scope %} *({{ commit.scope }})*{% endif %}\
  {%- if commit.breaking %} **BREAKING**{% endif %}
{%- endfor %}
{% endfor -%}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
  { message = "^chore: quick update", skip = true },
  { message = "^fix: barry quick fix", skip = true },
  { message = "^fix\\(commit\\)", skip = true },
  { message = "^feat", group = "🚀 Features" },
  { message = "^fix", group = "🐛 Bug Fixes" },
  { message = "^perf", group = "⚡ Performance" },
  { message = "^refactor", group = "♻️ Refactor" },
  { message = "^docs", group = "📖 Documentation" },
  { message = "^style", group = "🎨 Style" },
  { message = "^test", group = "🧪 Tests" },
  { message = "^build", group = "🔧 Build" },
  { message = "^ci", group = "🏗️ CI" },
  { message = "^chore", group = "🔧 Chore" },
  { message = "^revert", group = "⏪ Revert" },
]
filter_commits = false
tag_pattern = "v[0-9]*"
sort_commits = "newest"
