### gid.ABitOfEverythingService.Create
POST http://localhost:8080/v1/example/a_bit_of_everything/{float_value}/{double_value}/{int64_value}/separator/{uint64_value}/{int32_value}/{fixed64_value}/{fixed32_value}/{bool_value}/{string_value=strprefix/*}/{uint32_value}/{sfixed32_value}/{sfixed64_value}/{sint32_value}/{sint64_value}/{nonConventionalNameValue}/{enum_value}
Content-Type: application/json

{
 "bool_value": "",
 "bytes_value": "",
 "double_value": "",
 "enum_value": "",
 "enum_value_annotation": "",
 "fixed32_value": "",
 "fixed64_value": "",
 "float_value": "",
 "int32_value": "",
 "int64_override_type": "",
 "int64_value": "",
 "map_value": "",
 "mapped_nested_value": "",
 "mapped_string_value": "",
 "nested": "",
 "nested_annotation": "",
 "nonConventionalNameValue": "",
 "optional_string_value": "",
 "output_only_string_via_field_behavior_annotation": "",
 "repeated_enum_annotation": "",
 "repeated_enum_value": "",
 "repeated_nested_annotation": "",
 "repeated_string_annotation": "",
 "repeated_string_value": "",
 "required_string_via_field_behavior_annotation": "",
 "sfixed32_value": "",
 "sfixed64_value": "",
 "single_nested": "",
 "sint32_value": "",
 "sint64_value": "",
 "string_value": "",
 "timestamp_value": "",
 "uint32_value": "",
 "uint64_value": "",
 "uuid": ""
}

### gid.ABitOfEverythingService.CreateBody
POST http://localhost:8080/v1/example/a_bit_of_everything
Content-Type: application/json

{
 "bool_value": "",
 "bytes_value": "",
 "double_value": "",
 "enum_value": "",
 "enum_value_annotation": "",
 "fixed32_value": "",
 "fixed64_value": "",
 "float_value": "",
 "int32_value": "",
 "int64_override_type": "",
 "int64_value": "",
 "map_value": "",
 "mapped_nested_value": "",
 "mapped_string_value": "",
 "nested": "",
 "nested_annotation": "",
 "nonConventionalNameValue": "",
 "optional_string_value": "",
 "output_only_string_via_field_behavior_annotation": "",
 "repeated_enum_annotation": "",
 "repeated_enum_value": "",
 "repeated_nested_annotation": "",
 "repeated_string_annotation": "",
 "repeated_string_value": "",
 "required_string_via_field_behavior_annotation": "",
 "sfixed32_value": "",
 "sfixed64_value": "",
 "single_nested": "",
 "sint32_value": "",
 "sint64_value": "",
 "string_value": "",
 "timestamp_value": "",
 "uint32_value": "",
 "uint64_value": "",
 "uuid": ""
}

### gid.ABitOfEverythingService.CreateBook
POST http://localhost:8080/v1/{parent=publishers/*}/books
Content-Type: application/json

{
 "book": "",
 "book_id": "",
 "parent": ""
}

### gid.ABitOfEverythingService.UpdateBook
PATCH http://localhost:8080/v1/{book.name=publishers/*/books/*}
Content-Type: application/json

{
 "allow_missing": "",
 "book": "",
 "update_mask": ""
}

### gid.ABitOfEverythingService.Update
PUT http://localhost:8080/v1/example/a_bit_of_everything/{uuid}
Content-Type: application/json

{
 "bool_value": "",
 "bytes_value": "",
 "double_value": "",
 "enum_value": "",
 "enum_value_annotation": "",
 "fixed32_value": "",
 "fixed64_value": "",
 "float_value": "",
 "int32_value": "",
 "int64_override_type": "",
 "int64_value": "",
 "map_value": "",
 "mapped_nested_value": "",
 "mapped_string_value": "",
 "nested": "",
 "nested_annotation": "",
 "nonConventionalNameValue": "",
 "optional_string_value": "",
 "output_only_string_via_field_behavior_annotation": "",
 "repeated_enum_annotation": "",
 "repeated_enum_value": "",
 "repeated_nested_annotation": "",
 "repeated_string_annotation": "",
 "repeated_string_value": "",
 "required_string_via_field_behavior_annotation": "",
 "sfixed32_value": "",
 "sfixed64_value": "",
 "single_nested": "",
 "sint32_value": "",
 "sint64_value": "",
 "string_value": "",
 "timestamp_value": "",
 "uint32_value": "",
 "uint64_value": "",
 "uuid": ""
}

### gid.ABitOfEverythingService.UpdateV2
PUT http://localhost:8080/v2/example/a_bit_of_everything/{abe.uuid}
Content-Type: application/json

{
 "abe": "",
 "update_mask": ""
}

### gid.ABitOfEverythingService.GetQuery
GET http://localhost:8080/v1/example/a_bit_of_everything/query/{uuid}
Content-Type: application/json

### gid.ABitOfEverythingService.GetRepeatedQuery
GET http://localhost:8080/v1/example/a_bit_of_everything_repeated/{path_repeated_float_value}/{path_repeated_double_value}/{path_repeated_int64_value}/{path_repeated_uint64_value}/{path_repeated_int32_value}/{path_repeated_fixed64_value}/{path_repeated_fixed32_value}/{path_repeated_bool_value}/{path_repeated_string_value}/{path_repeated_bytes_value}/{path_repeated_uint32_value}/{path_repeated_enum_value}/{path_repeated_sfixed32_value}/{path_repeated_sfixed64_value}/{path_repeated_sint32_value}/{path_repeated_sint64_value}
Content-Type: application/json

### gid.ABitOfEverythingService.DeepPathEcho
POST http://localhost:8080/v1/example/deep_path/{single_nested.name}
Content-Type: application/json

{
 "bool_value": "",
 "bytes_value": "",
 "double_value": "",
 "enum_value": "",
 "enum_value_annotation": "",
 "fixed32_value": "",
 "fixed64_value": "",
 "float_value": "",
 "int32_value": "",
 "int64_override_type": "",
 "int64_value": "",
 "map_value": "",
 "mapped_nested_value": "",
 "mapped_string_value": "",
 "nested": "",
 "nested_annotation": "",
 "nonConventionalNameValue": "",
 "optional_string_value": "",
 "output_only_string_via_field_behavior_annotation": "",
 "repeated_enum_annotation": "",
 "repeated_enum_value": "",
 "repeated_nested_annotation": "",
 "repeated_string_annotation": "",
 "repeated_string_value": "",
 "required_string_via_field_behavior_annotation": "",
 "sfixed32_value": "",
 "sfixed64_value": "",
 "single_nested": "",
 "sint32_value": "",
 "sint64_value": "",
 "string_value": "",
 "timestamp_value": "",
 "uint32_value": "",
 "uint64_value": "",
 "uuid": ""
}

### gid.ABitOfEverythingService.NoBindings
POST http://localhost:8080/gid/a-bit-of-everything-service/no-bindings
Content-Type: application/json

{
 "nanos": "",
 "seconds": ""
}

### gid.ABitOfEverythingService.Timeout
GET http://localhost:8080/v2/example/timeout
Content-Type: application/json

### gid.ABitOfEverythingService.ErrorWithDetails
GET http://localhost:8080/v2/example/errorwithdetails
Content-Type: application/json

### gid.ABitOfEverythingService.GetMessageWithBody
POST http://localhost:8080/v2/example/withbody/{id}
Content-Type: application/json

{
 "data": "",
 "id": ""
}

### gid.ABitOfEverythingService.PostWithEmptyBody
POST http://localhost:8080/v2/example/postwithemptybody/{name}
Content-Type: application/json

{
 "name": ""
}

### gid.ABitOfEverythingService.CheckGetQueryParams
GET http://localhost:8080/v1/example/a_bit_of_everything/params/get/{single_nested.name}
Content-Type: application/json

### gid.ABitOfEverythingService.CheckNestedEnumGetQueryParams
GET http://localhost:8080/v1/example/a_bit_of_everything/params/get/nested_enum/{single_nested.ok}
Content-Type: application/json

### gid.ABitOfEverythingService.CheckPostQueryParams
POST http://localhost:8080/v1/example/a_bit_of_everything/params/post/{string_value}
Content-Type: application/json

{
 "bool_value": "",
 "bytes_value": "",
 "double_value": "",
 "enum_value": "",
 "enum_value_annotation": "",
 "fixed32_value": "",
 "fixed64_value": "",
 "float_value": "",
 "int32_value": "",
 "int64_override_type": "",
 "int64_value": "",
 "map_value": "",
 "mapped_nested_value": "",
 "mapped_string_value": "",
 "nested": "",
 "nested_annotation": "",
 "nonConventionalNameValue": "",
 "optional_string_value": "",
 "output_only_string_via_field_behavior_annotation": "",
 "repeated_enum_annotation": "",
 "repeated_enum_value": "",
 "repeated_nested_annotation": "",
 "repeated_string_annotation": "",
 "repeated_string_value": "",
 "required_string_via_field_behavior_annotation": "",
 "sfixed32_value": "",
 "sfixed64_value": "",
 "single_nested": "",
 "sint32_value": "",
 "sint64_value": "",
 "string_value": "",
 "timestamp_value": "",
 "uint32_value": "",
 "uint64_value": "",
 "uuid": ""
}

### gid.ABitOfEverythingService.OverwriteResponseContentType
GET http://localhost:8080/v2/example/overwriteresponsecontenttype
Content-Type: application/json

### gid.ABitOfEverythingService.CheckStatus
GET http://localhost:8080/v1/example/checkStatus
Content-Type: application/json

