// Code generated by protoc-gen-lava. DO NOT EDIT.
// versions:
// - protoc-gen-lava v0.1.0
// - protoc         v3.17.3
// source: proto/hello/example.proto

package hello

import (
	binding "github.com/pubgo/lava/pkg/binding"
	fiber "github.com/pubgo/lava/pkg/builder/fiber"
	grpcc "github.com/pubgo/lava/plugins/grpcc"
	xgen "github.com/pubgo/lava/xgen"
	byteutil "github.com/pubgo/x/byteutil"
	xerror "github.com/pubgo/xerror"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

func GetUserServiceClient(srv string, opts ...func(cfg *grpcc.Cfg)) func(func(cli UserServiceClient)) error {
	client := grpcc.GetClient(srv, opts...)
	return func(fn func(cli UserServiceClient)) (err error) {
		defer xerror.RespErr(&err)

		c, err := client.Get()
		if err != nil {
			return xerror.WrapF(err, "srv: %s", srv)
		}

		fn(&userServiceClient{c})
		return
	}
}
func init() {
	var mthList []xgen.GrpcRestHandler
	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &User{},
		Output:       &emptypb.Empty{},
		Service:      "hello.UserService",
		Name:         "AddUser",
		Method:       "POST",
		Path:         "/api/v1/users",
		DefaultUrl:   false,
		ClientStream: false,
		ServerStream: false,
	})
	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &User{},
		Output:       &emptypb.Empty{},
		Service:      "hello.UserService",
		Name:         "GetUser",
		Method:       "GET",
		Path:         "/api/v1/users",
		DefaultUrl:   false,
		ClientStream: false,
		ServerStream: false,
	})
	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &ListUsersRequest{},
		Output:       &User{},
		Service:      "hello.UserService",
		Name:         "ListUsers",
		Method:       "GET",
		Path:         "/api/v1/users",
		DefaultUrl:   false,
		ClientStream: false,
		ServerStream: true,
	})
	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &UserRole{},
		Output:       &User{},
		Service:      "hello.UserService",
		Name:         "ListUsersByRole",
		Method:       "GET",
		Path:         "/api/v1/users/role",
		DefaultUrl:   false,
		ClientStream: true,
		ServerStream: true,
	})
	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &UpdateUserRequest{},
		Output:       &User{},
		Service:      "hello.UserService",
		Name:         "UpdateUser",
		Method:       "PATCH",
		Path:         "/api/v1/users/{user.id}",
		DefaultUrl:   false,
		ClientStream: false,
		ServerStream: false,
	})
	xgen.Add(reflect.ValueOf(RegisterUserServiceServer), mthList)
	xgen.Add(reflect.ValueOf(RegisterUserServiceRestServer), mthList)
	xgen.Add(reflect.ValueOf(RegisterUserServiceHandlerServer), nil)
}
func RegisterUserServiceRestServer(app fiber.Router, server UserServiceServer) {
	xerror.Assert(app == nil || server == nil, "app or server is nil")
	app.Add("POST", "/api/v1/users", func(ctx *fiber.Ctx) error {
		var req = new(User)
		xerror.Panic(ctx.BodyParser(req))
		var resp, err = server.AddUser(ctx.UserContext(), req)
		xerror.Panic(err)
		return xerror.Wrap(ctx.JSON(resp))
	})
	app.Add("GET", "/api/v1/users", func(ctx *fiber.Ctx) error {
		var req = new(User)
		data := make(map[string][]string)
		ctx.Context().QueryArgs().VisitAll(func(key []byte, val []byte) {
			k := byteutil.ToStr(key)
			v := byteutil.ToStr(val)
			data[k] = append(data[k], v)
		})
		xerror.Panic(binding.MapFormByTag(req, data, "json"))
		var resp, err = server.GetUser(ctx.UserContext(), req)
		xerror.Panic(err)
		return xerror.Wrap(ctx.JSON(resp))
	})
	app.Add("PATCH", "/api/v1/users/{user.id}", func(ctx *fiber.Ctx) error {
		var req = new(UpdateUserRequest)
		xerror.Panic(ctx.BodyParser(req))
		var resp, err = server.UpdateUser(ctx.UserContext(), req)
		xerror.Panic(err)
		return xerror.Wrap(ctx.JSON(resp))
	})
}
