// Code generated by protoc-gen-lava. DO NOT EDIT.
// versions:
// - protoc-gen-lava v0.1.0
// - protoc         v3.19.4
// source: proto/user/user.proto

package gid

import (
	context "context"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpcc_builder "github.com/pubgo/lava/clients/grpcc/grpcc_builder"
	service "github.com/pubgo/lava/service"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

func InitUserClient(srv string) {
	grpcc_builder.InitClient(srv, (*UserClient)(nil), func(cc grpc.ClientConnInterface) interface{} { return NewUserClient(cc) })
}

func RegisterUser(srv service.Service, impl UserServer) {
	var desc service.Desc
	desc.Handler = impl
	desc.ServiceDesc = User_ServiceDesc
	desc.GrpcClientFn = NewUserClient

	desc.GrpcGatewayFn = func(mux *runtime.ServeMux) error {
		return RegisterUserHandlerServer(context.Background(), mux, impl)
	}

	srv.RegisterService(desc)
}

func InitABitOfEverythingServiceClient(srv string) {
	grpcc_builder.InitClient(srv, (*ABitOfEverythingServiceClient)(nil), func(cc grpc.ClientConnInterface) interface{} { return NewABitOfEverythingServiceClient(cc) })
}

func RegisterABitOfEverythingService(srv service.Service, impl ABitOfEverythingServiceServer) {
	var desc service.Desc
	desc.Handler = impl
	desc.ServiceDesc = ABitOfEverythingService_ServiceDesc
	desc.GrpcClientFn = NewABitOfEverythingServiceClient

	desc.GrpcGatewayFn = func(mux *runtime.ServeMux) error {
		return RegisterABitOfEverythingServiceHandlerServer(context.Background(), mux, impl)
	}

	srv.RegisterService(desc)
}

func InitCamelCaseServiceNameClient(srv string) {
	grpcc_builder.InitClient(srv, (*CamelCaseServiceNameClient)(nil), func(cc grpc.ClientConnInterface) interface{} { return NewCamelCaseServiceNameClient(cc) })
}

func RegisterCamelCaseServiceName(srv service.Service, impl CamelCaseServiceNameServer) {
	var desc service.Desc
	desc.Handler = impl
	desc.ServiceDesc = CamelCaseServiceName_ServiceDesc
	desc.GrpcClientFn = NewCamelCaseServiceNameClient

	desc.GrpcGatewayFn = func(mux *runtime.ServeMux) error {
		return RegisterCamelCaseServiceNameHandlerServer(context.Background(), mux, impl)
	}

	srv.RegisterService(desc)
}

func InitAnotherServiceWithNoBindingsClient(srv string) {
	grpcc_builder.InitClient(srv, (*AnotherServiceWithNoBindingsClient)(nil), func(cc grpc.ClientConnInterface) interface{} { return NewAnotherServiceWithNoBindingsClient(cc) })
}

func RegisterAnotherServiceWithNoBindings(srv service.Service, impl AnotherServiceWithNoBindingsServer) {
	var desc service.Desc
	desc.Handler = impl
	desc.ServiceDesc = AnotherServiceWithNoBindings_ServiceDesc
	desc.GrpcClientFn = NewAnotherServiceWithNoBindingsClient

	desc.GrpcGatewayFn = func(mux *runtime.ServeMux) error {
		return RegisterAnotherServiceWithNoBindingsHandlerServer(context.Background(), mux, impl)
	}

	srv.RegisterService(desc)
}
