### login.Code.SendCode
// 发送
POST http://localhost:8080/user/code/send-code
Content-Type: application/json

### login.Code.Verify
// 校验
POST http://localhost:8080/user/code/verify
Content-Type: application/json

### login.Code.IsCheckImageCode
// 是否校验图片验证码
POST http://localhost:8080/user/code/is-check-image-code
Content-Type: application/json

### login.Code.VerifyImageCode
// 校验图片验证码
POST http://localhost:8080/user/code/verify-image-code
Content-Type: application/json

### login.Code.GetSendStatus
// 获取发送状态
POST http://localhost:8080/user/code/get-send-status
Content-Type: application/json

