### hello.UserService.AddUser
, POST http://localhost:8080/api/v1/users
Content-Type: application/json

### hello.UserService.GetUser
, GET http://localhost:8080/api/v1/users
Content-Type: application/json

### hello.UserService.ListUsers
, GET http://localhost:8080/api/v1/users
Content-Type: application/json

### hello.UserService.ListUsersByRole
, GET http://localhost:8080/api/v1/users/role
Content-Type: application/json

### hello.UserService.UpdateUser
, PATCH http://localhost:8080/api/v1/users/{user.id}
Content-Type: application/json

