// Code generated by protoc-gen-lug. DO NOT EDIT.
// source: example/proto/hello/transport.proto

package hello

import (
	"reflect"
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/utils"
	fb "github.com/pubgo/lug/builder/fiber"
	"github.com/pubgo/lug/pkg/gutil"
	"github.com/pubgo/lug/plugins/grpcc"
	"github.com/pubgo/lug/xgen"
	"github.com/pubgo/xerror"
	"google.golang.org/grpc"
)

var _ = strings.Trim
var _ = utils.UnsafeString
var _ fiber.Router = nil
var _ = gutil.MapFormByTag
var _ = fb.Cfg{}

func GetTransportClient(srv string, optFns ...func(service string) []grpc.DialOption) func() (TransportClient, error) {
	client := grpcc.GetClient(srv, optFns...)
	return func() (TransportClient, error) {
		c, err := client.Get()
		return &transportClient{c}, xerror.WrapF(err, "srv: %s", srv)
	}
}

func init() {
	var mthList []xgen.GrpcRestHandler

	mthList = append(mthList, xgen.GrpcRestHandler{
		Service:      "hello.Transport",
		Name:         "TestStream",
		Method:       "POST",
		Path:         "/hello/transport/test-stream",
		ClientStream: "True" == "True",
		ServerStream: "True" == "True",
		DefaultUrl:   "True" == "True",
	})

	mthList = append(mthList, xgen.GrpcRestHandler{
		Service:      "hello.Transport",
		Name:         "TestStream1",
		Method:       "POST",
		Path:         "/hello/transport/test-stream1",
		ClientStream: "True" == "True",
		ServerStream: "False" == "True",
		DefaultUrl:   "True" == "True",
	})

	mthList = append(mthList, xgen.GrpcRestHandler{
		Service:      "hello.Transport",
		Name:         "TestStream2",
		Method:       "POST",
		Path:         "/hello/transport/test-stream2",
		ClientStream: "False" == "True",
		ServerStream: "True" == "True",
		DefaultUrl:   "True" == "True",
	})

	mthList = append(mthList, xgen.GrpcRestHandler{
		Service:      "hello.Transport",
		Name:         "TestStream3",
		Method:       "POST",
		Path:         "/hello/transport/test-stream3",
		ClientStream: "False" == "True",
		ServerStream: "False" == "True",
		DefaultUrl:   "True" == "True",
	})

	xgen.Add(reflect.ValueOf(RegisterTransportServer), mthList)
	xgen.Add(reflect.ValueOf(RegisterTransportRestServer), nil)
}

func RegisterTransportRestServer(app fiber.Router, server TransportServer) {
	xerror.Assert(app == nil || server == nil, "app is nil or server is nil")

	// websockets
	app.Get("/hello/transport/test-stream", fb.NewWs(func(ctx *fiber.Ctx, c *fb.Conn) {
		xerror.Panic(server.TestStream(&transportTestStreamServer{fb.NewWsStream(ctx, c)}))
	}))

	// websockets
	app.Get("/hello/transport/test-stream1", fb.NewWs(func(ctx *fiber.Ctx, c *fb.Conn) {
		xerror.Panic(server.TestStream1(&transportTestStream1Server{fb.NewWsStream(ctx, c)}))
	}))

	// websockets
	app.Get("/hello/transport/test-stream2", fb.NewWs(func(ctx *fiber.Ctx, c *fb.Conn) {
		var req = new(Message)
		data := make(map[string][]string)
		ctx.Context().QueryArgs().VisitAll(func(key []byte, val []byte) {
			k := utils.UnsafeString(key)
			v := utils.UnsafeString(val)
			if strings.Contains(v, ",") && gutil.EqualFieldType(req, reflect.Slice, k) {
				values := strings.Split(v, ",")
				for i := 0; i < len(values); i++ {
					data[k] = append(data[k], values[i])
				}
			} else {
				data[k] = append(data[k], v)
			}
		})

		xerror.Panic(gutil.MapFormByTag(req, data, "json"))
		xerror.Panic(server.TestStream2(req, &transportTestStream2Server{fb.NewWsStream(ctx, c)}))
	}))

	// restful
	app.Add("POST", "/hello/transport/test-stream3", func(ctx *fiber.Ctx) error {
		var req = new(Message)
		if err := ctx.BodyParser(req); err != nil {
			return xerror.Wrap(err)
		}

		var resp, err = server.TestStream3(ctx.UserContext(), req)
		if err != nil {
			return err
		}

		return ctx.JSON(resp)
	})

}
