package zrpcgen

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	defaultTimeoutMs = 3000
	zrpcImportPath   = "github.com/pubgo/lava/v2/pkg/zrpc"
	zrpcMethodField  = protowire.Number(50001)
)

type methodBinding struct {
	Subject   string
	Queue     string
	TimeoutMs uint32
}

func Generate(gen *protogen.Plugin) error {
	gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	for _, file := range gen.Files {
		if !file.Generate || len(file.Services) == 0 {
			continue
		}

		generateFile(gen, file)
	}

	return nil
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_zrpc.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	zrpc := protogen.GoImportPath(zrpcImportPath)

	g.P("// Code generated by protoc-gen-zrpc-go. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"fmt"`)
	g.P(`	"time"`)
	g.P()
	g.P(`	"github.com/nats-io/nats.go"`)
	g.P(`	"google.golang.org/protobuf/proto"`)
	g.P(")")
	g.P()

	for _, service := range file.Services {
		emitService(g, file, service, zrpc)
	}
}

func emitService(g *protogen.GeneratedFile, file *protogen.File, service *protogen.Service, zrpc protogen.GoImportPath) {
	protoPkg := string(file.Desc.Package())
	servicePath := fmt.Sprintf("%s.%s", protoPkg, service.GoName)
	defaultQueue := serviceDefaultQueue(service)

	g.P("// ", service.GoName, " zrpc subjects and queue defaults.")
	g.P("const (")
	g.P("	", service.GoName, "ServicePath = ", quote(servicePath))
	g.P("	", service.GoName, "DefaultQueue = ", quote(defaultQueue))
	for _, method := range service.Methods {
		opts := methodOptions(file, service, method)
		g.P("	", service.GoName, "_", method.GoName, "Subject = ", quote(opts.Subject))
	}
	g.P(")")
	g.P()

	g.P("type ", service.GoName, "Server interface {")
	for _, method := range service.Methods {
		in := g.QualifiedGoIdent(method.Input.GoIdent)
		out := g.QualifiedGoIdent(method.Output.GoIdent)
		g.P("	", method.GoName, "(ctx context.Context, req *", in, ") (*", out, ", error)")
	}
	g.P("}")
	g.P()

	g.P("func Register", service.GoName, "Server(nc *nats.Conn, impl ", service.GoName, "Server, queue string) (*", g.QualifiedGoIdent(zrpc.Ident("Server")), ", error) {")
	g.P("	if queue == \"\" {")
	g.P("		queue = ", service.GoName, "DefaultQueue")
	g.P("	}")
	g.P("	srv := ", g.QualifiedGoIdent(zrpc.Ident("NewServer")), "(nc)")
	for _, method := range service.Methods {
		emitRegisterUnary(g, service, method, zrpc)
	}
	g.P("	return srv, nil")
	g.P("}")
	g.P()

	g.P("type ", service.GoName, "Client struct {")
	g.P("	nc *nats.Conn")
	g.P("	timeout time.Duration")
	g.P("}")
	g.P()
	g.P("func New", service.GoName, "Client(nc *nats.Conn) *", service.GoName, "Client {")
	g.P("	return &", service.GoName, "Client{nc: nc, timeout: ", defaultTimeoutMs, " * time.Millisecond}")
	g.P("}")
	g.P()
	g.P("func (c *", service.GoName, "Client) WithTimeout(d time.Duration) *", service.GoName, "Client {")
	g.P("	c.timeout = d")
	g.P("	return c")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		emitClientMethod(g, service, method)
	}
}

func emitRegisterUnary(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, zrpc protogen.GoImportPath) {
	in := g.QualifiedGoIdent(method.Input.GoIdent)
	out := g.QualifiedGoIdent(method.Output.GoIdent)
	subject := fmt.Sprintf("%s_%sSubject", service.GoName, method.GoName)

	g.P("	if err := ", g.QualifiedGoIdent(zrpc.Ident("RegisterUnary")), "(srv, ", subject, ", queue,")
	g.P("		func() *", in, " { return &", in, "{} },")
	g.P("		func(ctx context.Context, req *", in, ") (*", out, ", error) {")
	g.P("			return impl.", method.GoName, "(ctx, req)")
	g.P("		},")
	g.P("	); err != nil {")
	g.P("		srv.Close()")
	g.P("		return nil, err")
	g.P("	}")
}

func emitClientMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	in := g.QualifiedGoIdent(method.Input.GoIdent)
	out := g.QualifiedGoIdent(method.Output.GoIdent)
	subject := fmt.Sprintf("%s_%sSubject", service.GoName, method.GoName)

	g.P("func (c *", service.GoName, "Client) ", method.GoName, "(ctx context.Context, req *", in, ") (*", out, ", error) {")
	g.P("	_ = ctx")
	g.P("	data, err := proto.Marshal(req)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	msg, err := c.nc.Request(", subject, ", data, c.timeout)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	if code := msg.Header.Get(", quote("Zrpc-Status-Code"), "); code != \"\" && code != \"0\" {")
	g.P("		return nil, fmt.Errorf(\"zrpc %s: %s\", code, msg.Header.Get(", quote("Zrpc-Status-Message"), "))")
	g.P("	}")
	g.P("	var resp ", out)
	g.P("	if err := proto.Unmarshal(msg.Data, &resp); err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	return &resp, nil")
	g.P("}")
	g.P()
}

func methodOptions(file *protogen.File, service *protogen.Service, method *protogen.Method) *methodBinding {
	out := &methodBinding{TimeoutMs: defaultTimeoutMs}
	if method.Desc.Options() == nil {
		return fillMethodDefaults(file, service, method, out)
	}

	if opts := decodeMethodOptions(method.Desc.Options().(*descriptorpb.MethodOptions)); opts != nil {
		out = opts
	}

	return fillMethodDefaults(file, service, method, out)
}

func fillMethodDefaults(file *protogen.File, service *protogen.Service, method *protogen.Method, out *methodBinding) *methodBinding {
	protoPkg := string(file.Desc.Package())
	if out.Subject == "" {
		out.Subject = fmt.Sprintf("svc.%s.%s/%s", protoPkg, service.GoName, method.GoName)
	}
	if out.Queue == "" {
		out.Queue = defaultQueueName(protoPkg, service.GoName)
	}
	if out.TimeoutMs == 0 {
		out.TimeoutMs = defaultTimeoutMs
	}

	return out
}

func serviceDefaultQueue(service *protogen.Service) string {
	for _, method := range service.Methods {
		if q := annotatedQueue(method); q != "" {
			return q
		}
	}

	return defaultQueueName(string(service.Desc.ParentFile().Package()), service.GoName)
}

func annotatedQueue(method *protogen.Method) string {
	if method.Desc.Options() == nil {
		return ""
	}

	opts := decodeMethodOptions(method.Desc.Options().(*descriptorpb.MethodOptions))
	if opts == nil {
		return ""
	}

	return opts.Queue
}

func decodeMethodOptions(opts *descriptorpb.MethodOptions) *methodBinding {
	if opts == nil {
		return nil
	}

	unknown := opts.ProtoReflect().GetUnknown()
	for len(unknown) > 0 {
		num, typ, n := protowire.ConsumeTag(unknown)
		if n < 0 {
			return nil
		}
		unknown = unknown[n:]

		if num != zrpcMethodField {
			m := protowire.ConsumeFieldValue(num, typ, unknown)
			if m < 0 {
				return nil
			}
			unknown = unknown[m:]
			continue
		}

		if typ != protowire.BytesType {
			m := protowire.ConsumeFieldValue(num, typ, unknown)
			if m < 0 {
				return nil
			}
			unknown = unknown[m:]
			continue
		}

		msg, m := protowire.ConsumeBytes(unknown)
		if m < 0 {
			return nil
		}

		return decodeMethodOptionsMessage(msg)
	}

	return nil
}

func decodeMethodOptionsMessage(raw []byte) *methodBinding {
	out := &methodBinding{TimeoutMs: defaultTimeoutMs}
	for len(raw) > 0 {
		num, typ, n := protowire.ConsumeTag(raw)
		if n < 0 {
			return nil
		}
		raw = raw[n:]

		switch num {
		case 1:
			if typ != protowire.BytesType {
				return nil
			}
			val, m := protowire.ConsumeString(raw)
			if m < 0 {
				return nil
			}
			out.Subject = val
			raw = raw[m:]
		case 2:
			if typ != protowire.BytesType {
				return nil
			}
			val, m := protowire.ConsumeString(raw)
			if m < 0 {
				return nil
			}
			out.Queue = val
			raw = raw[m:]
		case 3:
			if typ != protowire.VarintType {
				return nil
			}
			val, m := protowire.ConsumeVarint(raw)
			if m < 0 {
				return nil
			}
			out.TimeoutMs = uint32(val)
			raw = raw[m:]
		default:
			m := protowire.ConsumeFieldValue(num, typ, raw)
			if m < 0 {
				return nil
			}
			raw = raw[m:]
		}
	}

	return out
}

func defaultQueueName(pkg, service string) string {
	return strings.ToLower(pkg) + "." + strings.ToLower(service)
}

func quote(s string) string {
	return fmt.Sprintf("%q", s)
}
