// Code generated by protoc-gen-lava. DO NOT EDIT.
// versions:
// - protoc-gen-lava v0.1.0
// - protoc         v3.19.4
// source: proto/hello/transport.proto

package hellopb

import (
	context "context"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	grpcc_builder "github.com/pubgo/lava/clients/grpcc/grpcc_builder"
	inject "github.com/pubgo/lava/inject"
	service "github.com/pubgo/lava/service"
	xgen "github.com/pubgo/lava/xgen"
	fx "go.uber.org/fx"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

func InitTransportClient(addr string, alias ...string) {

	var name = ""
	if len(alias) > 0 {
		name = alias[0]
	}
	conn := grpcc_builder.NewClient(addr)

	inject.Register(fx.Provide(fx.Annotated{
		Target: func() TransportClient { return NewTransportClient(conn) },
		Name:   name,
	}))
}

func init() {
	var mthList []xgen.GrpcRestHandler
	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &Message{},
		Output:       &Message{},
		Service:      "hello.Transport",
		Name:         "TestStream",
		Method:       "",
		Path:         "",
		DefaultUrl:   false,
		ClientStream: true,
		ServerStream: true,
	})

	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &Message{},
		Output:       &Message{},
		Service:      "hello.Transport",
		Name:         "TestStream1",
		Method:       "",
		Path:         "",
		DefaultUrl:   false,
		ClientStream: true,
		ServerStream: false,
	})

	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &Message{},
		Output:       &Message{},
		Service:      "hello.Transport",
		Name:         "TestStream2",
		Method:       "",
		Path:         "",
		DefaultUrl:   false,
		ClientStream: false,
		ServerStream: true,
	})

	mthList = append(mthList, xgen.GrpcRestHandler{
		Input:        &Message{},
		Output:       &Message{},
		Service:      "hello.Transport",
		Name:         "TestStream3",
		Method:       "POST",
		Path:         "/hello/transport/test-stream3",
		DefaultUrl:   true,
		ClientStream: false,
		ServerStream: false,
	})

	xgen.Add(RegisterTransportServer, mthList)
}

func RegisterTransport(srv service.Service, impl TransportServer) {
	srv.RegService(service.Desc{
		Handler:     impl,
		ServiceDesc: Transport_ServiceDesc,
	})

	srv.RegGateway(func(ctx context.Context, mux *runtime.ServeMux, cc grpc.ClientConnInterface) error {
		return RegisterTransportHandlerClient(ctx, mux, NewTransportClient(cc))
	})

}
