// Code generated by protoc-gen-go-errors. DO NOT EDIT.
// versions:
// - protoc-gen-go-errors v0.0.4
// - protoc                 v4.24.3
// source: gid/id.proto

package gidpb

import (
	errors "github.com/pubgo/funk/errors"
	errorpb "github.com/pubgo/funk/proto/errorpb"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

var ErrCodeOK = &errorpb.ErrCode{
	BizCode: int32(0),
	Code:    errorpb.Code_OK,
	Name:    "gid.ok",
	Reason:  "ok",
}
var _ = errors.RegisterErrCodes(ErrCodeOK)

var ErrCodeIDGenerateFailed = &errorpb.ErrCode{
	BizCode: int32(100),
	Code:    errorpb.Code_Internal,
	Name:    "gid.id_generate_failed",
	Reason:  "id generate error",
}
var _ = errors.RegisterErrCodes(ErrCodeIDGenerateFailed)
