// Code generated by protoc-gen-golug. DO NOT EDIT.
// source: example/proto/login/code.proto
package login

import (
	"reflect"

	"github.com/pubgo/golug/golug_data"
)

func init() {
	golug_data.Add(reflect.ValueOf(RegisterCodeServer), `[{"method":"POST","name":"SendCode","path":"/user/code/send-code","client_stream":false,"server_streams":false},{"method":"POST","name":"Verify","path":"/user/code/verify","client_stream":false,"server_streams":false},{"method":"POST","name":"IsCheckImageCode","path":"/user/code/is-check-image-code","client_stream":false,"server_streams":false},{"method":"POST","name":"VerifyImageCode","path":"/user/code/verify-image-code","client_stream":false,"server_streams":false},{"method":"POST","name":"GetSendStatus","path":"/user/code/get-send-status","client_stream":false,"server_streams":false}]`)
}
