// Code generated by protoc-gen-lug. DO NOT EDIT.
// source: example/proto/login/login.proto

package login

import (
	"reflect"

	"github.com/pubgo/lug/client/grpcc"
	"github.com/pubgo/lug/xgen"
	"github.com/pubgo/xerror"
	"google.golang.org/grpc"
)

func GetLoginClient(srv string, optFns ...func(service string) []grpc.DialOption) func() (LoginClient, error) {
	client := grpcc.GetClient(srv, optFns...)
	return func() (LoginClient, error) {
		c, err := client.Get()
		return &loginClient{c}, xerror.WrapF(err, "srv: %s", srv)
	}
}

func init() {

	var mthList []xgen.GrpcRestHandler

	mthList = append(mthList, xgen.GrpcRestHandler{
		Service:       "login.Login",
		Name:          "Login",
		Method:        "POST",
		Path:          "/user/login/login",
		ClientStream:  "False" == "True",
		ServerStreams: "False" == "True",
	})

	mthList = append(mthList, xgen.GrpcRestHandler{
		Service:       "login.Login",
		Name:          "Authenticate",
		Method:        "POST",
		Path:          "/user/login/authenticate",
		ClientStream:  "False" == "True",
		ServerStreams: "False" == "True",
	})

	xgen.Add(reflect.ValueOf(RegisterLoginServer), mthList)

	xgen.Add(reflect.ValueOf(RegisterLoginHandlerFromEndpoint), nil)

}
