### gid.Id.Generate
// Generate 生成ID
POST http://localhost:8080/v1/id/generate
Content-Type: application/json

### gid.Id.Types
// Types id类型
GET http://localhost:8080/v1/id/types
Content-Type: application/json

