// Code generated by protoc-gen-twirp v8.1.2, DO NOT EDIT.
// source: hello/example.proto

// GoGo gRPC Example
// This example is used to show how to use gRPC and
// gRPC-Gateway with GoGo Protobuf.

package hellopb

import context "context"
import fmt "fmt"
import http "net/http"
import ioutil "io/ioutil"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

import google_protobuf2 "google.golang.org/protobuf/types/known/emptypb"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// =====================
// UserService Interface
// =====================

type UserService interface {
	AddUser(context.Context, *User) (*google_protobuf2.Empty, error)

	GetUser(context.Context, *User) (*google_protobuf2.Empty, error)

	ListUsers(context.Context, *ListUsersRequest) (*User, error)

	ListUsersByRole(context.Context, *UserRole) (*User, error)

	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
}

// ===========================
// UserService Protobuf Client
// ===========================

type userServiceProtobufClient struct {
	client      HTTPClient
	urls        [5]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewUserServiceProtobufClient creates a Protobuf client that implements the UserService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewUserServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) UserService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "hello", "UserService")
	urls := [5]string{
		serviceURL + "AddUser",
		serviceURL + "GetUser",
		serviceURL + "ListUsers",
		serviceURL + "ListUsersByRole",
		serviceURL + "UpdateUser",
	}

	return &userServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *userServiceProtobufClient) AddUser(ctx context.Context, in *User) (*google_protobuf2.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "AddUser")
	caller := c.callAddUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *User) (*google_protobuf2.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*User)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*User) when calling interceptor")
					}
					return c.callAddUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callAddUser(ctx context.Context, in *User) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceProtobufClient) GetUser(ctx context.Context, in *User) (*google_protobuf2.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "GetUser")
	caller := c.callGetUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *User) (*google_protobuf2.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*User)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*User) when calling interceptor")
					}
					return c.callGetUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callGetUser(ctx context.Context, in *User) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceProtobufClient) ListUsers(ctx context.Context, in *ListUsersRequest) (*User, error) {
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "ListUsers")
	caller := c.callListUsers
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListUsersRequest) (*User, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListUsersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListUsersRequest) when calling interceptor")
					}
					return c.callListUsers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callListUsers(ctx context.Context, in *ListUsersRequest) (*User, error) {
	out := new(User)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceProtobufClient) ListUsersByRole(ctx context.Context, in *UserRole) (*User, error) {
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "ListUsersByRole")
	caller := c.callListUsersByRole
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UserRole) (*User, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserRole)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserRole) when calling interceptor")
					}
					return c.callListUsersByRole(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callListUsersByRole(ctx context.Context, in *UserRole) (*User, error) {
	out := new(User)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceProtobufClient) UpdateUser(ctx context.Context, in *UpdateUserRequest) (*User, error) {
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateUser")
	caller := c.callUpdateUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateUserRequest) (*User, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateUserRequest) when calling interceptor")
					}
					return c.callUpdateUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceProtobufClient) callUpdateUser(ctx context.Context, in *UpdateUserRequest) (*User, error) {
	out := new(User)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =======================
// UserService JSON Client
// =======================

type userServiceJSONClient struct {
	client      HTTPClient
	urls        [5]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewUserServiceJSONClient creates a JSON client that implements the UserService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewUserServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) UserService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "hello", "UserService")
	urls := [5]string{
		serviceURL + "AddUser",
		serviceURL + "GetUser",
		serviceURL + "ListUsers",
		serviceURL + "ListUsersByRole",
		serviceURL + "UpdateUser",
	}

	return &userServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *userServiceJSONClient) AddUser(ctx context.Context, in *User) (*google_protobuf2.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "AddUser")
	caller := c.callAddUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *User) (*google_protobuf2.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*User)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*User) when calling interceptor")
					}
					return c.callAddUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callAddUser(ctx context.Context, in *User) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceJSONClient) GetUser(ctx context.Context, in *User) (*google_protobuf2.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "GetUser")
	caller := c.callGetUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *User) (*google_protobuf2.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*User)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*User) when calling interceptor")
					}
					return c.callGetUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callGetUser(ctx context.Context, in *User) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceJSONClient) ListUsers(ctx context.Context, in *ListUsersRequest) (*User, error) {
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "ListUsers")
	caller := c.callListUsers
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListUsersRequest) (*User, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListUsersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListUsersRequest) when calling interceptor")
					}
					return c.callListUsers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callListUsers(ctx context.Context, in *ListUsersRequest) (*User, error) {
	out := new(User)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceJSONClient) ListUsersByRole(ctx context.Context, in *UserRole) (*User, error) {
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "ListUsersByRole")
	caller := c.callListUsersByRole
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UserRole) (*User, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserRole)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserRole) when calling interceptor")
					}
					return c.callListUsersByRole(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callListUsersByRole(ctx context.Context, in *UserRole) (*User, error) {
	out := new(User)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *userServiceJSONClient) UpdateUser(ctx context.Context, in *UpdateUserRequest) (*User, error) {
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateUser")
	caller := c.callUpdateUser
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateUserRequest) (*User, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateUserRequest) when calling interceptor")
					}
					return c.callUpdateUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *userServiceJSONClient) callUpdateUser(ctx context.Context, in *UpdateUserRequest) (*User, error) {
	out := new(User)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==========================
// UserService Server Handler
// ==========================

type userServiceServer struct {
	UserService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewUserServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewUserServiceServer(svc UserService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwads compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &userServiceServer{
		UserService:      svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *userServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *userServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// UserServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const UserServicePathPrefix = "/twirp/hello.UserService/"

func (s *userServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "hello")
	ctx = ctxsetters.WithServiceName(ctx, "UserService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "hello.UserService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "AddUser":
		s.serveAddUser(ctx, resp, req)
		return
	case "GetUser":
		s.serveGetUser(ctx, resp, req)
		return
	case "ListUsers":
		s.serveListUsers(ctx, resp, req)
		return
	case "ListUsersByRole":
		s.serveListUsersByRole(ctx, resp, req)
		return
	case "UpdateUser":
		s.serveUpdateUser(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *userServiceServer) serveAddUser(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveAddUserJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveAddUserProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveAddUserJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "AddUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(User)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.AddUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *User) (*google_protobuf2.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*User)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*User) when calling interceptor")
					}
					return s.UserService.AddUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf2.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf2.Empty and nil error while calling AddUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveAddUserProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "AddUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(User)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.AddUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *User) (*google_protobuf2.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*User)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*User) when calling interceptor")
					}
					return s.UserService.AddUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf2.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf2.Empty and nil error while calling AddUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveGetUser(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetUserJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetUserProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveGetUserJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(User)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.GetUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *User) (*google_protobuf2.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*User)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*User) when calling interceptor")
					}
					return s.UserService.GetUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf2.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf2.Empty and nil error while calling GetUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveGetUserProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(User)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.GetUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *User) (*google_protobuf2.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*User)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*User) when calling interceptor")
					}
					return s.UserService.GetUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf2.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf2.Empty and nil error while calling GetUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveListUsers(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListUsersJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListUsersProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveListUsersJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListUsers")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListUsersRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.ListUsers
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListUsersRequest) (*User, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListUsersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListUsersRequest) when calling interceptor")
					}
					return s.UserService.ListUsers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *User
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *User and nil error while calling ListUsers. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveListUsersProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListUsers")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListUsersRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.ListUsers
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListUsersRequest) (*User, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListUsersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListUsersRequest) when calling interceptor")
					}
					return s.UserService.ListUsers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *User
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *User and nil error while calling ListUsers. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveListUsersByRole(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListUsersByRoleJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListUsersByRoleProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveListUsersByRoleJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListUsersByRole")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UserRole)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.ListUsersByRole
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UserRole) (*User, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserRole)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserRole) when calling interceptor")
					}
					return s.UserService.ListUsersByRole(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *User
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *User and nil error while calling ListUsersByRole. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveListUsersByRoleProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListUsersByRole")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UserRole)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.ListUsersByRole
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UserRole) (*User, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UserRole)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UserRole) when calling interceptor")
					}
					return s.UserService.ListUsersByRole(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *User
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *User and nil error while calling ListUsersByRole. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveUpdateUser(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUpdateUserJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUpdateUserProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *userServiceServer) serveUpdateUserJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UpdateUserRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.UserService.UpdateUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateUserRequest) (*User, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateUserRequest) when calling interceptor")
					}
					return s.UserService.UpdateUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *User
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *User and nil error while calling UpdateUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) serveUpdateUserProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateUser")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UpdateUserRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.UserService.UpdateUser
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateUserRequest) (*User, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateUserRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateUserRequest) when calling interceptor")
					}
					return s.UserService.UpdateUser(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*User)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*User) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *User
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *User and nil error while calling UpdateUser. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *userServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *userServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.2"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *userServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "hello", "UserService")
}

var twirpFileDescriptor1 = []byte{
	// 757 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6f, 0xc3, 0x34,
	0x14, 0x9d, 0xdb, 0x75, 0xa3, 0xee, 0xc6, 0x3a, 0xf3, 0xb1, 0x52, 0x06, 0x0b, 0x05, 0xa4, 0xaa,
	0x52, 0x93, 0xae, 0x08, 0x34, 0x75, 0x0f, 0xd3, 0x4a, 0xcb, 0x36, 0xa0, 0x80, 0xb2, 0x0f, 0x24,
	0x5e, 0x2a, 0xb7, 0xb9, 0x4b, 0xad, 0xa5, 0x71, 0x66, 0x3b, 0x15, 0x15, 0xe2, 0x85, 0x77, 0x5e,
	0x80, 0x37, 0x7e, 0x16, 0x3f, 0x00, 0x09, 0xf1, 0xca, 0x7f, 0x40, 0x76, 0xd2, 0xb2, 0x66, 0x1b,
	0xda, 0x53, 0x2c, 0x9f, 0x73, 0xcf, 0xb9, 0x3e, 0xbe, 0x0e, 0x7e, 0x6d, 0x02, 0x41, 0xc0, 0x1d,
	0xf8, 0x9e, 0x4e, 0xa3, 0x00, 0xec, 0x48, 0x70, 0xc5, 0x49, 0xc1, 0x6c, 0x56, 0xdf, 0xf6, 0x39,
	0xf7, 0x03, 0x70, 0xcc, 0xe6, 0x28, 0xbe, 0x75, 0x60, 0x1a, 0xa9, 0x79, 0xc2, 0xa9, 0x1e, 0x64,
	0x41, 0xc5, 0xa6, 0x20, 0x15, 0x9d, 0x46, 0x29, 0xe1, 0xdd, 0x2c, 0xc1, 0x8b, 0x05, 0x55, 0x8c,
	0x87, 0x29, 0x6e, 0x65, 0xf1, 0x5b, 0x06, 0x81, 0x37, 0x9c, 0x52, 0x79, 0x97, 0x32, 0xf6, 0xb3,
	0x0c, 0xa9, 0x44, 0x3c, 0x56, 0x19, 0x94, 0x46, 0xcc, 0xa1, 0x61, 0xc8, 0x95, 0x11, 0x97, 0x29,
	0x9a, 0x7c, 0xc6, 0x4d, 0x1f, 0xc2, 0x26, 0x8f, 0x20, 0xa4, 0x11, 0x9b, 0xb5, 0x1d, 0x1e, 0x19,
	0xce, 0x13, 0xfc, 0xf7, 0x7d, 0xde, 0x34, 0xab, 0xe6, 0x8c, 0x06, 0xcc, 0xa3, 0x8a, 0x0b, 0xe9,
	0x2c, 0x97, 0x09, 0xa9, 0xf6, 0x3b, 0xc2, 0xeb, 0xd7, 0x12, 0x04, 0xf9, 0x18, 0xe7, 0x98, 0x57,
	0x41, 0x16, 0xaa, 0x6f, 0x77, 0x3f, 0xfc, 0xeb, 0xcf, 0x83, 0xf7, 0xca, 0x6b, 0x8d, 0x77, 0x2e,
	0x7a, 0xd6, 0x34, 0x96, 0xca, 0x1a, 0x81, 0x45, 0xad, 0x88, 0x4b, 0xa6, 0xd8, 0x0c, 0x2c, 0x16,
	0x2a, 0xf0, 0x41, 0xb8, 0x39, 0xe6, 0x91, 0x03, 0xbc, 0x2e, 0x78, 0x00, 0x95, 0x9c, 0x85, 0xea,
	0xaf, 0xb6, 0x4b, 0xb6, 0x89, 0xd9, 0x76, 0x79, 0x00, 0xae, 0x01, 0xc8, 0x31, 0x2e, 0x8d, 0x05,
	0x50, 0x05, 0x43, 0x8f, 0x2a, 0xa8, 0xe4, 0x2d, 0x54, 0x2f, 0xb5, 0xab, 0x76, 0x72, 0x52, 0x7b,
	0x91, 0x83, 0x7d, 0xb5, 0x88, 0xda, 0xc5, 0x09, 0xbd, 0x47, 0x15, 0xd4, 0xfe, 0x41, 0xf8, 0x15,
	0xdd, 0x9d, 0xd6, 0x5b, 0x5a, 0xa1, 0xe7, 0xac, 0x5a, 0xb8, 0x10, 0x30, 0xa9, 0xa4, 0x69, 0xe6,
	0x29, 0x93, 0x2f, 0x99, 0x54, 0x37, 0x34, 0x88, 0xc1, 0x4d, 0x88, 0xe4, 0x13, 0xbc, 0x39, 0x01,
	0xea, 0x81, 0x90, 0x95, 0xbc, 0x95, 0xaf, 0x97, 0xda, 0xfb, 0xa9, 0xea, 0xc2, 0xd4, 0x3e, 0x4f,
	0xe0, 0x7e, 0xa8, 0xc4, 0xdc, 0x5d, 0x90, 0xab, 0x37, 0x78, 0xeb, 0x21, 0x40, 0xca, 0x38, 0x7f,
	0x07, 0x73, 0xd3, 0x59, 0xd1, 0xd5, 0x4b, 0xdd, 0xcb, 0x4c, 0x3b, 0xbd, 0xa4, 0x17, 0x43, 0xec,
	0xe4, 0x8e, 0x50, 0xed, 0x1e, 0xef, 0x5e, 0x47, 0x3a, 0x27, 0xe3, 0x0f, 0xf7, 0x31, 0x48, 0xa5,
	0xcf, 0x1d, 0x4b, 0x10, 0x46, 0xbd, 0xb4, 0x3c, 0xb7, 0x61, 0x18, 0x40, 0x47, 0x1c, 0x9b, 0x2a,
	0x33, 0x69, 0xcf, 0x3a, 0x7e, 0xa6, 0x87, 0x71, 0x40, 0xe5, 0x9d, 0x8b, 0x13, 0xba, 0x5e, 0xd7,
	0x7e, 0x46, 0xb8, 0xac, 0x7b, 0xd1, 0x7a, 0x72, 0x61, 0x79, 0x82, 0xb7, 0x93, 0x5b, 0xf0, 0x86,
	0x92, 0x85, 0x63, 0x48, 0xbd, 0xff, 0xef, 0xda, 0xb6, 0xd2, 0x82, 0x4b, 0xcd, 0x27, 0x47, 0x18,
	0xf3, 0xc0, 0x03, 0x31, 0x54, 0x13, 0x1a, 0xa6, 0x1d, 0xbd, 0xf5, 0xa8, 0xba, 0x97, 0x3e, 0x1f,
	0xb7, 0x68, 0xc8, 0x57, 0x13, 0x1a, 0x36, 0xea, 0x78, 0xdd, 0xdc, 0x76, 0x11, 0x17, 0xce, 0xae,
	0xfb, 0x97, 0x57, 0xe5, 0x35, 0x82, 0xf1, 0xc6, 0xa0, 0x3f, 0xe8, 0xf6, 0xdd, 0x32, 0xd2, 0xdb,
	0xa7, 0xbd, 0xc1, 0xc5, 0x57, 0xe5, 0x5c, 0xfb, 0xb7, 0x3c, 0x2e, 0xe9, 0xae, 0x2f, 0x41, 0xcc,
	0xd8, 0x18, 0xc8, 0x39, 0xde, 0x3c, 0xf5, 0x3c, 0x33, 0xcc, 0x0f, 0x43, 0xaa, 0xbe, 0xf9, 0xc8,
	0xb7, 0xaf, 0x1f, 0x7d, 0xad, 0xf2, 0xd3, 0x1f, 0x7f, 0xff, 0x9a, 0x23, 0xb5, 0x6d, 0xf3, 0xde,
	0x66, 0x87, 0x8e, 0x0e, 0x53, 0x76, 0x50, 0x83, 0xf4, 0xf1, 0xe6, 0x19, 0xa8, 0x97, 0x2b, 0xbd,
	0x61, 0x94, 0x76, 0xc8, 0xaa, 0x12, 0xf9, 0x1c, 0x17, 0x97, 0xc9, 0x92, 0xbd, 0x54, 0x28, 0x9b,
	0x75, 0xf5, 0xa1, 0xc3, 0x33, 0x4a, 0x2d, 0x44, 0xbe, 0xc6, 0x3b, 0xcb, 0xca, 0xee, 0xdc, 0x24,
	0xb4, 0x93, 0x99, 0xd5, 0x55, 0xa5, 0xaa, 0x51, 0x7a, 0x9d, 0x90, 0x15, 0x25, 0x47, 0x3f, 0x94,
	0x3a, 0x6a, 0x21, 0xf2, 0x2d, 0xc6, 0xff, 0x8d, 0x1a, 0xa9, 0x2c, 0x4a, 0xb3, 0xd3, 0xb7, 0x2a,
	0x5a, 0x33, 0xa2, 0xfb, 0xed, 0xbd, 0x55, 0xd1, 0x1f, 0xf4, 0xc7, 0x66, 0xde, 0x8f, 0x1d, 0xd4,
	0xe8, 0xd2, 0xef, 0x76, 0x6d, 0xc7, 0xd4, 0x44, 0xa3, 0xe3, 0xf4, 0xfb, 0xcb, 0xe9, 0x17, 0xa4,
	0xd0, 0xce, 0x1f, 0xda, 0xad, 0x06, 0xca, 0x89, 0x13, 0xbc, 0xe7, 0xbb, 0xdf, 0x7c, 0x6a, 0xa5,
	0x7f, 0x68, 0x4b, 0x80, 0xf9, 0xb5, 0x70, 0x31, 0x27, 0x1f, 0x4c, 0x94, 0x8a, 0x64, 0xc7, 0x71,
	0x7c, 0xa6, 0x26, 0xf1, 0xc8, 0x1e, 0xf3, 0xa9, 0xe3, 0x73, 0x9f, 0x3b, 0xbe, 0x88, 0xc6, 0xcd,
	0xb4, 0x60, 0xb4, 0x61, 0xf2, 0xff, 0xe8, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x70, 0x11,
	0xcc, 0xea, 0x05, 0x00, 0x00,
}
