### gid.LoginService.Login
POST http://localhost:8080/v1/example/login
Content-Type: application/json

{
 "password": "",
 "username": ""
}

### gid.LoginService.Logout
POST http://localhost:8080/v1/example/logout
Content-Type: application/json

{
 "stringarray": "",
 "test": "",
 "timeoflogout": ""
}

