# Gateway server settings (servers/gatewayserver).
gateway_server:
  enable_print_router: true
  # websocket_port: 8081
  # websocket_origin_patterns:
  #   - "https://*.example.com"
  # http: {}
  # grpc: {}
