// Code generated by protoc-gen-resty. DO NOT EDIT.
// versions:
// - protoc-gen-resty v0.1.0
// - protoc           v3.19.4
// source: proto/hello/api.proto

package hello

import (
	context "context"
	v2 "github.com/go-resty/resty/v2"
	go_json "github.com/goccy/go-json"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
)

type TestApiResty interface {
	// Version rpc
	Version(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error)
	Version1(ctx context.Context, in *structpb.Value, opts ...func(req *v2.Request)) (*TestApiOutput1, error)
	// VersionTest rpc
	VersionTest(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error)
	// VersionTest rpc custom
	VersionTestCustom(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error)
}

func NewTestApiResty(client *v2.Client) TestApiResty {
	client.SetContentLength(true)
	return &testApiResty{client: client}
}

type testApiResty struct {
	client *v2.Client
}

func (c *testApiResty) Version(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	if in != nil {
		var rv = reflect.ValueOf(in).Elem()
		var rt = reflect.TypeOf(in).Elem()
		for i := 0; i < rt.NumField(); i++ {
			if val, ok := rt.Field(i).Tag.Lookup("param"); ok && val != "" {
				req.SetPathParam(val, rv.Field(i).String())
				continue
			}
			if val, ok := rt.Field(i).Tag.Lookup("query"); ok && val != "" {
				req.SetQueryParam(val, rv.Field(i).String())
				continue
			}
			if val, ok := rt.Field(i).Tag.Lookup("json"); ok && val != "" {
				req.SetQueryParam(val, rv.Field(i).String())
			}
		}
	}
	var resp, err = req.Execute("GET", "/v1/version")
	if err != nil {
		return nil, err
	}
	out := new(TestApiOutput)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiResty) Version1(ctx context.Context, in *structpb.Value, opts ...func(req *v2.Request)) (*TestApiOutput1, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	var body map[string]interface{}
	if in != nil {
		var rv = reflect.ValueOf(in).Elem()
		var rt = reflect.TypeOf(in).Elem()
		for i := 0; i < rt.NumField(); i++ {
			if val, ok := rt.Field(i).Tag.Lookup("param"); ok && val != "" {
				req.SetPathParam(val, rv.Field(i).String())
				continue
			}
			if val, ok := rt.Field(i).Tag.Lookup("query"); ok && val != "" {
				req.SetQueryParam(val, rv.Field(i).String())
				continue
			}
			if body == nil {
				body = make(map[string]interface{})
			}
			if val, ok := rt.Field(i).Tag.Lookup("json"); ok && val != "" {
				body[val] = rv.Field(i).String()
			}
		}
	}
	req.SetBody(body)
	var resp, err = req.Execute("POST", "/v1/version1")
	if err != nil {
		return nil, err
	}
	out := new(TestApiOutput1)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiResty) VersionTest(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	if in != nil {
		var rv = reflect.ValueOf(in).Elem()
		var rt = reflect.TypeOf(in).Elem()
		for i := 0; i < rt.NumField(); i++ {
			if val, ok := rt.Field(i).Tag.Lookup("param"); ok && val != "" {
				req.SetPathParam(val, rv.Field(i).String())
				continue
			}
			if val, ok := rt.Field(i).Tag.Lookup("query"); ok && val != "" {
				req.SetQueryParam(val, rv.Field(i).String())
				continue
			}
			if val, ok := rt.Field(i).Tag.Lookup("json"); ok && val != "" {
				req.SetQueryParam(val, rv.Field(i).String())
			}
		}
	}
	var resp, err = req.Execute("GET", "/v1/example/versiontest")
	if err != nil {
		return nil, err
	}
	out := new(TestApiOutput)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiResty) VersionTestCustom(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	if in != nil {
		var rv = reflect.ValueOf(in).Elem()
		var rt = reflect.TypeOf(in).Elem()
		for i := 0; i < rt.NumField(); i++ {
			if val, ok := rt.Field(i).Tag.Lookup("param"); ok && val != "" {
				req.SetPathParam(val, rv.Field(i).String())
				continue
			}
			if val, ok := rt.Field(i).Tag.Lookup("query"); ok && val != "" {
				req.SetQueryParam(val, rv.Field(i).String())
				continue
			}
			if val, ok := rt.Field(i).Tag.Lookup("json"); ok && val != "" {
				req.SetQueryParam(val, rv.Field(i).String())
			}
		}
	}
	var resp, err = req.Execute("GET", "/v1/example/versionTestCustom")
	if err != nil {
		return nil, err
	}
	out := new(TestApiOutput)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}

type TestApiV2Resty interface {
	Version1(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error)
	VersionTest1(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error)
}

func NewTestApiV2Resty(client *v2.Client) TestApiV2Resty {
	client.SetContentLength(true)
	return &testApiV2Resty{client: client}
}

type testApiV2Resty struct {
	client *v2.Client
}

func (c *testApiV2Resty) Version1(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	var body map[string]interface{}
	if in != nil {
		var rv = reflect.ValueOf(in).Elem()
		var rt = reflect.TypeOf(in).Elem()
		for i := 0; i < rt.NumField(); i++ {
			if val, ok := rt.Field(i).Tag.Lookup("param"); ok && val != "" {
				req.SetPathParam(val, rv.Field(i).String())
				continue
			}
			if val, ok := rt.Field(i).Tag.Lookup("query"); ok && val != "" {
				req.SetQueryParam(val, rv.Field(i).String())
				continue
			}
			if body == nil {
				body = make(map[string]interface{})
			}
			if val, ok := rt.Field(i).Tag.Lookup("json"); ok && val != "" {
				body[val] = rv.Field(i).String()
			}
		}
	}
	req.SetBody(body)
	var resp, err = req.Execute("POST", "/v2/example/version/{name}")
	if err != nil {
		return nil, err
	}
	out := new(TestApiOutput)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiV2Resty) VersionTest1(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	var body map[string]interface{}
	if in != nil {
		var rv = reflect.ValueOf(in).Elem()
		var rt = reflect.TypeOf(in).Elem()
		for i := 0; i < rt.NumField(); i++ {
			if val, ok := rt.Field(i).Tag.Lookup("param"); ok && val != "" {
				req.SetPathParam(val, rv.Field(i).String())
				continue
			}
			if val, ok := rt.Field(i).Tag.Lookup("query"); ok && val != "" {
				req.SetQueryParam(val, rv.Field(i).String())
				continue
			}
			if body == nil {
				body = make(map[string]interface{})
			}
			if val, ok := rt.Field(i).Tag.Lookup("json"); ok && val != "" {
				body[val] = rv.Field(i).String()
			}
		}
	}
	req.SetBody(body)
	var resp, err = req.Execute("POST", "/v2/example/versiontest")
	if err != nil {
		return nil, err
	}
	out := new(TestApiOutput)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}
