// Code generated by protoc-gen-resty. DO NOT EDIT.
// versions:
// - protoc-gen-resty v0.1.0
// - protoc           v3.17.3
// source: proto/hello/api.proto

package hello

import (
	context "context"
	fmt "fmt"
	v2 "github.com/go-resty/resty/v2"
	go_json "github.com/goccy/go-json"
	structpb "google.golang.org/protobuf/types/known/structpb"
	http "net/http"
	reflect "reflect"
	strings "strings"
)

type TestApiResty interface {
	// Version rpc
	Version(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error)
	Version1(ctx context.Context, in *structpb.Value, opts ...func(req *v2.Request)) (*TestApiOutput1, error)
	// VersionTest rpc
	VersionTest(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error)
	// VersionTest rpc custom
	VersionTestCustom(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error)
}

func NewTestApiResty(client *v2.Client) TestApiResty {
	return &testApiResty{client: client}
}

type testApiResty struct {
	client *v2.Client
}

func (c *testApiResty) Version(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	var rv = reflect.ValueOf(in)
	var rt = reflect.TypeOf(in)
	for i := rt.NumField(); i > 0; i-- {
		if path := rt.Field(i).Tag.Get("path"); path != "" {
			req.SetPathParam(path, rv.Field(i).String())
		}
		if uri := rt.Field(i).Tag.Get("uri"); uri != "" {
			req.SetQueryParam(uri, rv.Field(i).String())
		}
		if uri := rt.Field(i).Tag.Get("json"); uri != "" {
			req.SetQueryParam(uri, rv.Field(i).String())
		}
	}
	var resp, err = req.Execute("GET", "/v1/version")
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("code error: %d", resp.StatusCode())
	}
	out := new(TestApiOutput)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiResty) Version1(ctx context.Context, in *structpb.Value, opts ...func(req *v2.Request)) (*TestApiOutput1, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	var rv = reflect.ValueOf(in)
	var rt = reflect.TypeOf(in)
	for i := rt.NumField(); i > 0; i-- {
		if path := rt.Field(i).Tag.Get("path"); path != "" {
			req.SetPathParam(path, rv.Field(i).String())
		}
		if uri := rt.Field(i).Tag.Get("uri"); uri != "" {
			req.SetQueryParam(uri, rv.Field(i).String())
		}
	}
	req.SetBody(in)
	var resp, err = req.Execute("POST", "/v1/version1")
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("code error: %d", resp.StatusCode())
	}
	out := new(TestApiOutput1)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiResty) VersionTest(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	var rv = reflect.ValueOf(in)
	var rt = reflect.TypeOf(in)
	for i := rt.NumField(); i > 0; i-- {
		if path := rt.Field(i).Tag.Get("path"); path != "" {
			req.SetPathParam(path, rv.Field(i).String())
		}
		if uri := rt.Field(i).Tag.Get("uri"); uri != "" {
			req.SetQueryParam(uri, rv.Field(i).String())
		}
		if uri := rt.Field(i).Tag.Get("json"); uri != "" {
			req.SetQueryParam(uri, rv.Field(i).String())
		}
	}
	var resp, err = req.Execute("GET", "/v1/example/versiontest")
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("code error: %d", resp.StatusCode())
	}
	out := new(TestApiOutput)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiResty) VersionTestCustom(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	var rv = reflect.ValueOf(in)
	var rt = reflect.TypeOf(in)
	for i := rt.NumField(); i > 0; i-- {
		if path := rt.Field(i).Tag.Get("path"); path != "" {
			req.SetPathParam(path, rv.Field(i).String())
		}
		if uri := rt.Field(i).Tag.Get("uri"); uri != "" {
			req.SetQueryParam(uri, rv.Field(i).String())
		}
		if uri := rt.Field(i).Tag.Get("json"); uri != "" {
			req.SetQueryParam(uri, rv.Field(i).String())
		}
	}
	var resp, err = req.Execute("GET", "/v1/example/versionTestCustom")
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("code error: %d", resp.StatusCode())
	}
	out := new(TestApiOutput)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}

type TestApiV2Resty interface {
	Version1(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error)
	VersionTest1(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error)
}

func NewTestApiV2Resty(client *v2.Client) TestApiV2Resty {
	return &testApiV2Resty{client: client}
}

type testApiV2Resty struct {
	client *v2.Client
}

func (c *testApiV2Resty) Version1(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	var rv = reflect.ValueOf(in)
	var rt = reflect.TypeOf(in)
	for i := rt.NumField(); i > 0; i-- {
		if path := rt.Field(i).Tag.Get("path"); path != "" {
			req.SetPathParam(path, rv.Field(i).String())
		}
		if uri := rt.Field(i).Tag.Get("uri"); uri != "" {
			req.SetQueryParam(uri, rv.Field(i).String())
		}
	}
	req.SetBody(in)
	var resp, err = req.Execute("POST", "/v2/example/version/{name}")
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("code error: %d", resp.StatusCode())
	}
	out := new(TestApiOutput)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testApiV2Resty) VersionTest1(ctx context.Context, in *TestReq, opts ...func(req *v2.Request)) (*TestApiOutput, error) {
	var req = c.client.R()
	if ctx != nil {
		req.SetContext(ctx)
	}
	for i := range opts {
		opts[i](req)
	}
	var rv = reflect.ValueOf(in)
	var rt = reflect.TypeOf(in)
	for i := rt.NumField(); i > 0; i-- {
		if path := rt.Field(i).Tag.Get("path"); path != "" {
			req.SetPathParam(path, rv.Field(i).String())
		}
		if uri := rt.Field(i).Tag.Get("uri"); uri != "" {
			req.SetQueryParam(uri, rv.Field(i).String())
		}
	}
	req.SetBody(in)
	var resp, err = req.Execute("POST", "/v2/example/versiontest")
	if err != nil {
		return nil, err
	}
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("code error: %d", resp.StatusCode())
	}
	out := new(TestApiOutput)
	if err := go_json.Unmarshal(resp.Body(), out); err != nil {
		return nil, err
	}
	return out, nil
}
