// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/sqlx/code.proto

package sqlx

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/pubgo/lava/proto/lava"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SendCodeRequest) Validate() error {
	return nil
}
func (this *SendCodeResponse) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *VerifyRequest) Validate() error {
	return nil
}
func (this *VerifyResponse) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *IsCheckImageCodeRequest) Validate() error {
	return nil
}
func (this *IsCheckImageCodeResponse) Validate() error {
	return nil
}
func (this *VerifyImageCodeRequest) Validate() error {
	return nil
}
func (this *VerifyImageCodeResponse) Validate() error {
	return nil
}
func (this *GetSendStatusRequest) Validate() error {
	return nil
}
func (this *GetSendStatusResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *SendStatus) Validate() error {
	return nil
}
