### sqlx.Code.SendCode
, // 发送POST http://localhost:8080/user/code/send-code
Content-Type: application/json

### sqlx.Code.Verify
, // 校验POST http://localhost:8080/user/code/verify
Content-Type: application/json

### sqlx.Code.IsCheckImageCode
, // 是否校验图片验证码POST http://localhost:8080/user/code/is-check-image-code
Content-Type: application/json

### sqlx.Code.VerifyImageCode
, // 校验图片验证码POST http://localhost:8080/user/code/verify-image-code
Content-Type: application/json

### sqlx.Code.GetSendStatus
, // 获取发送状态POST http://localhost:8080/user/code/get-send-status
Content-Type: application/json

