name: Lint & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v4"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          skip-go-installation: true
          args: --timeout 3m --verbose

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Collect dependencies
        run: |
          go mod download
          go install gotest.tools/gotestsum@latest

      - name: Run unit tests
        run: gotestsum --junitfile unit-tests.xml -- -gcflags=-l ./...

      - name: Test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test report
          path: unit-tests.xml
          reporter: java-junit
          fail-on-error: false
