// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/hello/helloworld.proto

package hello

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	time "time"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *HelloRequest) Validate() error {
	if this.StrVal != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.StrVal); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("StrVal", err)
		}
	}
	if this.FloatVal != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.FloatVal); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("FloatVal", err)
		}
	}
	if this.DoubleVal != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.DoubleVal); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("DoubleVal", err)
		}
	}
	if this.BoolVal != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.BoolVal); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("BoolVal", err)
		}
	}
	if this.BytesVal != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.BytesVal); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("BytesVal", err)
		}
	}
	if this.Int32Val != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Int32Val); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Int32Val", err)
		}
	}
	if this.Uint32Val != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Uint32Val); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Uint32Val", err)
		}
	}
	if this.Int64Val != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Int64Val); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Int64Val", err)
		}
	}
	if this.Uint64Val != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Uint64Val); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Uint64Val", err)
		}
	}
	return nil
}
func (this *HelloReply) Validate() error {
	return nil
}
